name: flutx_core
description: "Core logical library for flutx"
version: 0.0.9
homepage:

environment:
  sdk: ^3.9.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  yaml_edit: ^2.2.2
  path: ^1.9.1
  dart_style: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0



flutter:


